### ISSUE TITLE
pmap doesnt actually parallelize anymore

### ISSUE THREAD

**Issue by dmacd** [hcarvalhoalves/python-pmap#2]
Did you mean to use pool.imap instead of itertools.imap in core.py:95?

**Comment by hcarvalhoalves** [comment]
Yep, latest release is incorrect... I'm investigating.

**Comment by liabifano** [comment]
The screenshot of the test below shows evidences that `pmap` is still parallelizing.
<img width="597" alt="screen shot 2017-03-03 at 2 02 42 pm" src="https://cloud.githubusercontent.com/assets/12484009/23560702/21a3b4ce-001a-11e7-9926-32533900a9e4.png">

**Comment by hcarvalhoalves** [comment]
@liabifano your test is not correct because `pmap` is not being evaluated (it returns a generator). If you wrap in `list` and use a slower function other than `x+1` you'll see it's serial like `map`.

There's a fix on https://github.com/hcarvalhoalves/python-pmap/pull/3
